// console.log (Math.random() * 10)



// console.log("|_______|_______|\n|_______|_______|\n|_______|_______|\n|_______|_______|") 
// console.log("|_______|_______|\n|_______|_______|\n|_______|_______|\n|_______|_______|") 
// console.log("|_______|_______|\n|_______|_______|\n|_______|_______|\n|_______|_______|") 
// console.log("|_______|_______|\n|_______|_______|\n|_______|_______|\n|_______|_______|") 


// console.log("All Around the World".charAt(7).toUpperCase());



// activity1

// let Name = "Kathleen";
// let age = "25";
// let color = "green";

// console.log(`Hi my Name is ${Name}. I am ${age} and my favourie color is ${color}.`)

// age = 24;
// color = `blackpink`;

// console.log(`Hi I am ${age} and my favourie color is ${color}.`)



// activity 2

// let breakfast = "toast";
// let lunch = "Pot noodle";
// let dinner = "burgers";

// console.log(`Good day! This morning I will eat ${breakfast} for breakfast, ${lunch} for lunch and for dinner I will have ${dinner} to eat.`)



// Activity 3




// const b = birthDate();

// console.log ( new Date().getTime() )


// console.log ( new Date("12-01-2024").getTime() )

const todaysDate = new Date().getTime();

const birthday = new Date("12-Jan-2024").getTime();

let timeUntilBDay = birthday - todaysDate;

console.log( timeUntilBDay/(1000 * 60))
console.log( timeUntilBDay/(1000 * 60 * 60))
console.log( timeUntilBDay/(1000 * 60 * 60 *24))


// let birthday = 01/12/97;
// let today = 01/16/23;

// console.log = (birthDate)



// Activity 4

// let space1 = `X`
// let space2 = `O`
// let space3 = ` `

// console.log(`|_______|________|\n|_______|_______|\n|_______|_______|\n|_______|_______|`)
// console.log(`|_______|________|\n|_______|_______|\n|_______|_______|\n|_______|_______|`)
// console.log(`|_______|__${space1}____|\n|_______|_______|\n|_______|_______|\n|_______|_______|`)


// console.log( Math.floor( Math.random() * 10 ) )

